export const FETCH_SANBAY = 'FETCH_SANBAY';
export const FETCH_CHUYENBAY = 'FETCH_CHUYENBAY';
export const SEARCH_FLIGHT = 'SEARCH_FLIGHT';
export const FIND_ONE_CHUYENBAY = 'FIND_ONE_CHUYENBAY';
export const BOOKING_CHUYENBAY = 'BOOKING_CHUYENBAY';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';